### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by Hoishin** [nodecg/react-hooks#250]
`useSomething` is a conventional name for hooks, but it's not ideal for npm package names because of  vagueness. There are number of options but I'm leaning to `@nodecg/react-hooks`

**Comment by tobybaratta** [comment]
+1 on the rename of the package to `@nodecg/react-hooks`.

Please if you do rename will you mark the prior package as deprecated (either through `npm deprecate` or the UI)? Just so then people know to update, if there is anything to update too.
